# Generated by Django 4.2.3 on 2023-07-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_remove_plastic_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plastic',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shopapp.product'),
        ),
    ]
