# Generated by Django 4.2.3 on 2023-07-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_name_alter_plastic_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shopapp.product')),
            ],
        ),
    ]
