# Generated by Django 4.2.3 on 2023-07-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_printer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
