# Generated by Django 4.2.3 on 2023-07-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_plastic_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.nameproductproperty')),
            ],
            options={
                'verbose_name': 'Свойство продукта',
                'verbose_name_plural': 'Свойства продукта',
            },
        ),
        migrations.CreateModel(
            name='ValueProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plastic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='plastic',
            name='product',
        ),
        migrations.RemoveField(
            model_name='plastic',
            name='type',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='product',
        ),
        migrations.DeleteModel(
            name='ColorPlastic',
        ),
        migrations.DeleteModel(
            name='Plastic',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='TypePlastic',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.valueproductproperty'),
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(related_name='products', to='shopapp.productproperty'),
        ),
    ]
